In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('matches.csv')  # read the added csv file

In [29]:
df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [30]:
df.columns #all columns names

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [31]:
df.head

<bound method NDFrame.head of         id    Season           city        date                        team1  \
0        1  IPL-2017      Hyderabad  05-04-2017          Sunrisers Hyderabad
1        2  IPL-2017           Pune  06-04-2017               Mumbai Indians
2        3  IPL-2017         Rajkot  07-04-2017                Gujarat Lions
3        4  IPL-2017         Indore  08-04-2017       Rising Pune Supergiant
4        5  IPL-2017      Bangalore  08-04-2017  Royal Challengers Bangalore
..     ...       ...            ...         ...                          ...
751  11347  IPL-2019         Mumbai  05-05-2019        Kolkata Knight Riders
752  11412  IPL-2019        Chennai  07-05-2019          Chennai Super Kings
753  11413  IPL-2019  Visakhapatnam  08-05-2019          Sunrisers Hyderabad
754  11414  IPL-2019  Visakhapatnam  10-05-2019               Delhi Capitals
755  11415  IPL-2019      Hyderabad  12-05-2019               Mumbai Indians

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
1         Rising Pune Supergiant       Rising Pune Supergiant         field
2          Kolkata Knight Riders        Kolkata Knight Riders         field
3                Kings XI Punjab              Kings XI Punjab         field
4               Delhi Daredevils  Royal Challengers Bangalore           bat
..                           ...                          ...           ...
751               Mumbai Indians               Mumbai Indians         field
752               Mumbai Indians          Chennai Super Kings           bat
753               Delhi Capitals               Delhi Capitals         field
754          Chennai Super Kings          Chennai Super Kings         field
755          Chennai Super Kings               Mumbai Indians           bat

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
1    normal           0       Rising Pune Supergiant            0
2    normal           0        Kolkata Knight Riders            0
3    normal           0              Kings XI Punjab            0
4    normal           0  Royal Challengers Bangalore           15
..      ...         ...                          ...          ...
751  normal           0               Mumbai Indians            0
752  normal           0               Mumbai Indians            0
753  normal           0               Delhi Capitals            0
754  normal           0          Chennai Super Kings            0
755  normal           0               Mumbai Indians            1

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh
1                 7       SPD Smith
2                10         CA Lynn
3                 6      GJ Maxwell
4                 0       KM Jadhav
..              ...             ...
751               9       HH Pandya
752               6        AS Yadav
753               2         RR Pant
754               6    F du Plessis
755               0       JJ Bumrah

                                         venue         umpire1  \
0    Rajiv Gandhi International Stadium, Uppal     AY Dandekar
1      Maharashtra Cricket Association Stadium  A Nand Kishore
2       Saurashtra Cricket Association Stadium     Nitin Menon
3                       Holkar Cricket Stadium    AK Chaudhary
4                        M Chinnaswamy Stadium             NaN
..                                         ...             ...
751                           Wankhede Stadium   Nanda Kishore
752                  M. A. Chidambaram Stadium     Nigel Llong
753                           ACA-VDCA Stadium             NaN
754                           ACA-VDCA Stadium   Sundaram Ravi
755         Rajiv Gandhi Intl. Cricket Stadium     Nitin Menon

            umpire2                  umpire3
0          NJ Llong                      NaN
1            S Ravi                      NaN
2         CK Nandan                      NaN
3     C Shamshuddin                      NaN
4               NaN                      NaN
..              ...                      ...
751        O Nandan                   S Ravi
752     Nitin Menon                Ian Gould
753             NaN                      NaN
754  Bruce Oxenford  Chettithody Shamshuddin
755       Ian Gould              Nigel Llong

[756 rows x 18 columns]>

In [32]:
df.shape # to find the rows and columns

(756, 18)

In [40]:
df.describe()

                 id  dl_applied  win_by_runs  win_by_wickets
count    756.000000  756.000000   756.000000      756.000000
mean    1792.178571    0.025132    13.283069        3.350529
std     3464.478148    0.156630    23.471144        3.387963
min        1.000000    0.000000     0.000000        0.000000
25%      189.750000    0.000000     0.000000        0.000000
50%      378.500000    0.000000     0.000000        4.000000
75%      567.250000    0.000000    19.000000        6.000000
max    11415.000000    1.000000   146.000000       10.000000

In [42]:
print(' rows present:',df.shape[0])
print(' columns present:',df.shape[1])

 rows present: 756
 columns present: 18

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   Season           756 non-null    object
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(4), object(14)
memory usage: 106.4+ KB

In [46]:
print (' the total is' ,df.info() )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   Season           756 non-null    object
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(4), object(14)
memory usage: 106.4+ KB
 the total is None

In [52]:
df.loc[:2]  # for the row slice only 0 to 2

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN

In [50]:
df.iloc[:2] # index loc means starts by index

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [56]:
df.tail(1)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [58]:
print('Total number of rows:',df.shape[0],'\nTotal number of columns:',df.shape[1])

Total number of rows: 756
Total number of columns: 18